# Generated by Django 2.0.5 on 2018-07-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCalendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='MyCalendar',
        ),
    ]
