# Generated by Django 2.0.5 on 2018-07-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCalendar', '0002_auto_20180703_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycalendar',
            options={'managed': False},
        ),
    ]
