# Generated by Django 2.0.5 on 2018-07-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCalendar', '0003_auto_20180703_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycalendar',
            options={'managed': True},
        ),
    ]
